title:             Kuture Blog
email:             austinkuture@126.com
description:       Austin Kuture 's Blog
author:            Kuture
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://www.kuture.com.cn"

# Social Profiles
twitter_username:  AustinKuture
github_username:   AustinKuture
facebook_username: AustinKuture

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
