# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.kuture.com.cn
date_format: "ordinal"
title: Kuture
subtitle: "汲众言者博识，阅众家者博学。"
description: "Kuture的个人博客"
keywords: Kuture, yakun, AI, Pytorch, Keras, Tensorflow, Python, Spider, austinkuture, iOS, Objective-C, Swift
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
leancloud:
  enable: true
  app_id: OuqtgYuaTMxmXSBx310IKuWY-gzGzoHsz
  app_key: AAiznz9nMSOA8uJqrJ9Cay6v
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i> 访问人数
  site_uv_footer: 人次 
  # # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i> 总访问量
  site_pv_footer: 次 
  # custom pv span for one page only
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i> 阅读
  page_pv_footer: 次 

# ---------------- #
#      Author      #
# ---------------- #
author: Yakun
# organization: kuture.com.cn
# organization_url: http://www.kuture.com.cn
github_username: AustinKuture
location: BeiJing, China
email: austinkuture@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 百科

  #-#
    #href: /links/#
    #label: 链接#

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
# subscribe_rss: /feed.xml #

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: AustinKuture/austinkuture.github.io

# ---------------- #
#      Comments    #
# ---------------- #
#support provider: disqus, gitment, gitalk
comment:
  gitment:AustinKuture


# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
